# Generated by Django 4.1.11 on 2023-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_userinfo_track_alter_userinfo_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='utc_time',
            field=models.CharField(default='2023-09-07T14:02:03Z', max_length=100),
        ),
    ]
