# Generated by Django 4.1.11 on 2023-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_alter_userinfo_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='utc_time',
            field=models.CharField(default='2023-09-07T16:40:54Z', max_length=100),
        ),
    ]
